### ISSUE TITLE
Hi, I tried my data set and the effect seems to be very poor. Is it because your pre training model has too few times?

### ISSUE THREAD

**Issue by baixinping618** [SenHe/Flow-Style-VTON#1]
Hi, I tried my data set and the effect seems to be very poor. Is it because your pre training model has too few times?

**Comment by SenHe** [comment]
Hi,

If you want to try your own dataset, you need to re-train the model on your dataset.

**Comment by baixinping618** [comment]
Do different characters have to be trained? Can't this apply to a different character?

**Comment by SenHe** [comment]
It depends on whether the person images (fashion models with clean background, well aligned in the image center?) and garment images (shirt only?) in your dataset are the same as those in the VITON dataset.

**Comment by baixinping618** [comment]
ok   thanks

**Comment by puhuk** [comment]
@baixinping618  Hi, May I ask how did you make densepose files with densepose?
