### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by ZyadMohamed1** [SenHe/Flow-Style-VTON#13]
I trained my Custom dataset and it gave bad results
I prepared the data as a VITON dataset and changed the learning rate to 0.00001.
For VITON Dataset it gives good results.

Here are some of my Custom dataset results

![Screenshot 2022-06-02 134311](https://user-images.githubusercontent.com/53688189/171623155-988bb6d4-8d4b-477e-ab3b-b08c12a4d881.png)

![Screenshot 2022-06-02 134410](https://user-images.githubusercontent.com/53688189/171623261-a4f21125-af93-45b7-8008-fde3426de8d6.png)

**Comment by SenHe** [comment]
It is interesting the code works for [others dataset](https://github.com/SenHe/Flow-Style-VTON/issues/5) but not works for your dataset.
From the above results, it seems that the target garment hasn't been warped and is not the same as the one fed into your warping network.

**Comment by SenHe** [comment]
I also don't know why this is happening.
The code works for me on custom dataset with more diverse person images and more categories of garment.

**Comment by ZyadMohamed1** [comment]
I trained it on 21 epoch so is that maybe the error or it doesn't matter?

**Comment by ZyadMohamed1** [comment]
![Screenshot 2022-06-02 170907](https://user-images.githubusercontent.com/53688189/171661282-737793d8-285c-4836-a02e-ecad0ae05444.png)

This is the last result so the wrapping is not working

**Comment by ZyadMohamed1** [comment]
![Screenshot 2022-06-02 170907](https://user-images.githubusercontent.com/53688189/171661422-4838e45a-5a2f-4374-93ae-3a29fdab9dce.png)

this is the last result so the wrapping is not working

**Comment by tengolagan** [comment]
Hi @ZyadMohamed1 how did you manage to get the npy for train_densepose ?
