### ISSUE TITLE
poor output

### ISSUE THREAD

**Issue by Ibrahimatef** [SenHe/Flow-Style-VTON#2]
Hi, Thanks For your code and efforts!
I tried to replicate your results using `aug` and `non-aug` model, but output was very poor even using `VITON_test` dataset and `no-aug` model which should be better

Output Samples using non-aug model and VITON_test :

![1](https://user-images.githubusercontent.com/36816214/162237877-5cde2145-ba85-43e5-b6ca-730d42de2c06.jpg)
![2](https://user-images.githubusercontent.com/36816214/162237896-8383e0ab-3ff9-4803-98d8-06950c767802.jpg)
![3](https://user-images.githubusercontent.com/36816214/162237898-6c6b6263-aca4-48f3-b8ae-564e5674c4a6.jpg)
![4](https://user-images.githubusercontent.com/36816214/162237901-5e36b7b2-c41e-4378-acc8-6defeeb8c025.jpg)
![5](https://user-images.githubusercontent.com/36816214/162237904-f142b0cd-a105-46e8-a8df-38ad08bab99f.jpg)
![6](https://user-images.githubusercontent.com/36816214/162237906-87886466-32e2-45c1-acb6-4c545cf6ecd8.jpg)

*Note : I think this [line](https://github.com/SenHe/Flow-Style-VTON/blob/dc3ddc5b16b1905c69acba8dfbe70ec66dcb91ec/test/data/aligned_dataset_test.py#L19) should be `dir_C = '_clothes'`*

**Comment by SenHe** [comment]
Please can you provide your inputs and intermediate warped garment?
I don't get these results from the code.

**Comment by Ibrahimatef** [comment]
I download [this folder](https://drive.google.com/file/d/1Y7uV0gomwWyxCvvH8TIbY7D9cTAUy6om/view) and modified test_pairs.txt to be like that :

![Capture](https://user-images.githubusercontent.com/36816214/162247670-55ade2c3-d4b8-438e-a4c4-2a63532cf152.JPG)

First Column is the name of original image and second column is name of clothes image as you created

**Comment by SenHe** [comment]
Hi,
I downloaded and run the code again, got the following results:
![000010_0](https://user-images.githubusercontent.com/25322508/162421760-c7d30168-43e9-43ac-9cb2-f682bc3065a5.jpg)
![000028_0](https://user-images.githubusercontent.com/25322508/162421807-742fc8a9-bce7-4b1f-92a6-303eddc7a296.jpg)
![000038_0](https://user-images.githubusercontent.com/25322508/162421825-aa87fb47-c9c2-4629-b5ff-401f9e3b6c01.jpg)
![000074_0](https://user-images.githubusercontent.com/25322508/162421831-948c8f7e-b69c-40da-b30e-8c1baa5f28cd.jpg)
![000048_0](https://user-images.githubusercontent.com/25322508/162421858-12199dfd-aa33-4017-b5e0-50b2ccc2c015.jpg)
![000057_0](https://user-images.githubusercontent.com/25322508/162421869-810be442-f6e2-4039-a9f2-921d13750327.jpg)
