### ISSUE TITLE
Checkpoints for teacher PB-AFN

### ISSUE THREAD

**Issue by JacksonCakes** [SenHe/Flow-Style-VTON#22]
Hi, thank you for your great work! May I know if you have checkpoints for Parser-based model? Do you have measure on the performance of PB-model as compared to PF model?

**Comment by SenHe** [comment]
I don't have the checkpoints for parser-based model.
You can train the first two stages to get it.

**Comment by Yomiko11** [comment]
> 嗨，感谢您的出色工作！我能否知道你们是否有基于 Parser 的模型的检查点？与 PF 模型相比，您是否测量了 PB 模型的性能？

Have you finished your training? Can you provide the weight model of PB and PF? The author only provides the weight model of PF
