### ISSUE TITLE
Couldn't replicate results 

### ISSUE THREAD

**Issue by Ibrahimatef** [SenHe/Flow-Style-VTON#3]
Hi Again,
I was trying again your code to make sure everything is right, I found that issue was closed :( 
Unfortunately, I couldn't solve the problem 
I got following results with saving person image, garment, flow, warped garment, and try-on image :

![1](https://user-images.githubusercontent.com/36816214/162636329-e43bd86d-81d0-4444-92b6-3f3ffa785120.jpg)
![2](https://user-images.githubusercontent.com/36816214/162636330-72ef3a0f-e47c-41f0-92c0-a601e4f93677.jpg)
![3](https://user-images.githubusercontent.com/36816214/162636331-2050671f-1307-46f6-a93b-29f78f2e5f6c.jpg)
![4](https://user-images.githubusercontent.com/36816214/162636332-5dd92d82-a143-4a13-885b-bbc18acda293.jpg)
![5](https://user-images.githubusercontent.com/36816214/162636333-2eccf314-a798-44ef-8150-aedb60e7643f.jpg)

Do you know what mistake could lead to this poor output or you could check the performance of uploaded pretrained models ? 
Here is command i used to replicate the results :
```
!python test.py --name demo \
                --resize_or_crop None --batchSize 1 --gpu_ids 0 \
                --warp_checkpoint ckp/non_aug/PFAFN_warp_epoch_101.pth \
                --gen_checkpoint ckp/non_aug/PFAFN_gen_epoch_101.pth \
                --dataroot 'VITON_test'
```

Also I think results are saved in our_t_results or im_gar_flow_wg folders which i have to create them manually

**Comment by SenHe** [comment]
I replied to you. Please check this link:
https://github.com/SenHe/Flow-Style-VTON/issues/2#issuecomment-1092735565

**Comment by Ibrahimatef** [comment]
I have read your reply and couldn't get your results though, that is why I opened this issue to check if something may be wrong

**Comment by SenHe** [comment]
I don't know what's wrong in your side - as I can reproduce the results with the GitHub code and the downloaded checkpoint.
What's your PyTorch version?

**Comment by Ibrahimatef** [comment]
I am using pytorch versions 1.10 with cuda 11.2

**Comment by SenHe** [comment]
OK.

I checked my environment for training and inference:
Python: 3.6.13
Torch: 1.1.0
Torchvision: 0.3.0

**Comment by Ibrahimatef** [comment]
Thank your for your help, I will check results with this environment

**Comment by Ibrahimatef** [comment]
I tried with your environment versions and results were very good, Thanks for your efforts and great work!

**Comment by taruntiwarihp** [comment]
Hi, I tried your environment version and I'm getting the very best results :(, Please guide me
Python: 3.6.13
Torch: 1.1.0
Torchvision: 0.3.0
Cuda 11.4

**Comment by tuallen** [comment]
Add `align_corners=True` to all occurrences of `F.grid_sample`. In newer versions of PyTorch, `F.grid_sample` now has `align_corners` set to `False` by default.

I obtained the same results as @SenHe on a RTX 3090 and the latest versions of Torch, Torchvision, and CUDA after adding the above change.

**Comment by caip1299920300** [comment]
After version 1.2.0 ：
Add ”align_corners=True“ parameter to all “F.grid_sample(）” functions in the code to solve the problem。
such as：flow = F.grid_sample(last_flow, flow, mode='bilinear', padding_mode='border',align_corners=True)
Get good results：
![000266_0](https://user-images.githubusercontent.com/60836278/219573462-98084c24-546e-4cb9-b036-49503b1f361c.jpg)

**Comment by 89lixx** [comment]
The FID is quite different from a RTX 3090. I got 9.37. Did you get the FID as the paper mentioned? @tuallen @caip1299920300

**Comment by caip1299920300** [comment]
yes,8.89
&nbsp;


☆·．快~~乐·╮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月21日(星期二) 下午4:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SenHe/Flow-Style-VTON] Couldn&#39;t replicate results  (Issue #3)





 
The FID is quite different from a RTX 3090. I got 9.37. Did you get the FID as the paper mentioned? @tuallen @caip1299920300

**Comment by 89lixx** [comment]
thanks!
