### ISSUE TITLE
Implementation of Eq.3 from paper is different in code

### ISSUE THREAD

**Issue by hamzarawal** [SenHe/Flow-Style-VTON#33]
Hi, in Eq.3 we get` fci` by modulated convolution of style `s` and garment warped by upsampled `fi-1`. But in the code, we are warping `last_flow` by current `flow`. Why do we need to warp one flow using another flow? My understanding based on the paper is that warping is used for garments only.

[`flow = F.grid_sample(last_flow, flow, mode='bilinear', padding_mode='border')`](https://github.com/SenHe/Flow-Style-VTON/blob/ed25d525a53fadaf3ea794d0beb6affbb75f8160/test/models/afwm.py#L448)

I also have another question. Why do we need to `apply_offset` to the predicted `flow`? Why don't we just treat the output of the network as flow?
[`flow = apply_offset(flow)`](https://github.com/SenHe/Flow-Style-VTON/blob/ed25d525a53fadaf3ea794d0beb6affbb75f8160/test/models/afwm.py#L441)

**Comment by SenHe** [comment]
please refer to [this question](https://github.com/geyuying/PF-AFN/issues/45)

**Comment by hamzarawal** [comment]
Thank you.
