### ISSUE TITLE
train_densepose

### ISSUE THREAD

**Issue by wang674** [SenHe/Flow-Style-VTON#34]
Hello, I converted them into. npy files and compared them with. npy files in the VITON dataset, but they still do not match.  What kind of densepose model does the author use？ @SenHe @dariussingh

**Comment by SenHe** [comment]
Can you give more context about your question?
The training dataset was downloaded [here](https://github.com/geyuying/PF-AFN). The authors didn't mention which ResNet backbone they used for DensePose extraction.
