### ISSUE TITLE
train question

### ISSUE THREAD

**Issue by Kuekua** [SenHe/Flow-Style-VTON#5]
hi， thanks for your excellent work!
I notice your project is based on PF-AFN. So, I use your warp module in my own dataset , the train project is PF-AFN. But after train several steps, the warp result is bad , the clothe is missing. I wonder why, I can train a good result used PF-AFN code. Please help me if convenient.

thanks

**Comment by Kuekua** [comment]
![58_0_6918740005478755084_4_0](https://user-images.githubusercontent.com/26383252/162893168-c10e6d7a-4203-4f9a-b83d-40dcdffc741b.jpg)

**Comment by SenHe** [comment]
Hi,

Please try a smaller learning rate on your own dataset [here](https://github.com/SenHe/Flow-Style-VTON/blob/a6a17405fe4d864ef1dd9d078fd9f2dd23b6ec35/train/options/train_options.py#L25). 
Maybe 0.00001.

**Comment by Kuekua** [comment]
thanks， it works
