### ISSUE TITLE
edge extractor

### ISSUE THREAD

**Issue by nourgana** [SenHe/Flow-Style-VTON#6]
what's the built in function used for edge extraction? thanks

**Comment by SenHe** [comment]
Please check [here](https://colab.research.google.com/drive/1HvSB2Mx8WZ-Wo_8FDrc05DaOi4QUE9hG) - Unet based garment segmentation, or [here](https://github.com/switchablenorms/DeepFashion_Try_On/issues/36#issuecomment-725679247) - opencv based garment image foreground extraction.
