### ISSUE TITLE
Problem with result

### ISSUE THREAD

**Issue by vladvdovin27** [SenHe/Flow-Style-VTON#7]
At the output, for some reason, it turns out that the sleeves are deformed incorrectly and they are not visible at all, what could this be related to? Example:
![41](https://user-images.githubusercontent.com/60712606/163822037-5d45d92d-9f86-47b7-83d1-1b773851be87.jpg)

**Comment by SenHe** [comment]
Please refer to [this issue](https://github.com/SenHe/Flow-Style-VTON/issues/3).

**Comment by vladvdovin27** [comment]
Thank you so much
