### ISSUE TITLE
generative adversarial loss

### ISSUE THREAD

**Issue by siarheidevel** [SenHe/Flow-Style-VTON#8]
Hello. Why you do not use generative adversarial loss?

**Comment by SenHe** [comment]
good question.
I didn't try it in the experiment but I thinks it's worth to try.
Note, this task is not similar to those GANs works which generate a new image from a random noise. Essentially, what we need to do in this task are two things:

1. warp the garment such that it is aligned with the human body.
2. fuse the warped garment and the person to generate the try-on image.

We are not generating anything new in this task!
That said, adversarial loss is still worth to try. I feel it will help to improve the realism of the try-on image when the warping and fusion is not perfect.

**Comment by siarheidevel** [comment]
We are generating intermedeate tutor image (p) and then image(t)
In this images we are generating unseen human parts (arms which were hidden by previous clothing)
Mayby using conditional gan like in pix2pixhd is worth to try.

Some random (with learnable amount value) noise can be added in bottleneck unet layer of the generator
